### ISSUE TITLE
configuration of welcome bot

### ISSUE THREAD

**Issue by Sloth-Panda** [proRamLOGO/quantum-algorithms#2]
welcome bot config file will be having a proper message that will show up when any user will open up an issue or pull-request for the first time.
For reference, check out and download the bot from here 

https://github.com/apps/welcome

**Comment by Sloth-Panda** [comment]
Would like to work on this as part of crossWoc

**Comment by Sloth-Panda** [comment]
can you add crosswoc tag too

**Comment by Sloth-Panda** [comment]
Hey @proRamLOGO , please add "crossWoc" tag to this issue else this wont be counted for points

**Comment by proRamLOGO** [comment]
Required Tags have been added
