### ISSUE TITLE
Code of Conduct and contributing files

### ISSUE THREAD

**Issue by Sloth-Panda** [proRamLOGO/quantum-algorithms#3]
This project is lacking a code of conduct and contributing file so would like to add those files

would like to work on this as part of crossWOC

**Comment by Sloth-Panda** [comment]
@proRamLOGO can you please add crossWoc tag too?

**Comment by Sloth-Panda** [comment]
Hey @proRamLOGO , please add "crossWoc" tag to this issue else this wont be counted for points

**Comment by proRamLOGO** [comment]
Required Tags have been added
