### ISSUE TITLE
Add Quantum Superposition Implementation | Q#

### ISSUE THREAD

**Issue by aryashah2k** [proRamLOGO/quantum-algorithms#35]
@proRamLOGO , in this issue, I shall add code implementation for Quantum Superposition in Q#

Do consider assigning this issue to me and I shall start my work right away!

Please add the relevant Label for Crosswoc for this issue

good-first-issue is 50 points
difficulty: easy is 100 points
difficulty: medium is 200 points
difficulty: hard is 500 points
Regards,
Arya

**Comment by proRamLOGO** [comment]
Will you be using the H gate of Q# or define a Hadamard function of your own and then use it ?

**Comment by aryashah2k** [comment]
I'll be using H gate of Q# in this issue and am planning to open separate issue with separate program for custom Hadamard function defined and then being used.

**Comment by proRamLOGO** [comment]
Sorry then this issue shall be closed as using H Gate is very basic and you have applied that in your earlier contributions already. Please try to make quality contributions as you did earlier.
