### ISSUE TITLE
I will add name and photo of maintainer in the end of readme file of your repo

### ISSUE THREAD

**Issue by yashlikescode** [proRamLOGO/quantum-algorithms#38]
like the one mentioned below
![image](https://user-images.githubusercontent.com/66861659/110197136-7f786b80-7e6f-11eb-92ff-91d450025fa1.png)

**Comment by proRamLOGO** [comment]
This issue is in continuation with #37 . 
Please refrain from adding add-ons to previous issues as separate issues. 
You could edit or post comments in the already posted issues as well.
