### ISSUE TITLE
Add Deutsch Josza Algorithm + Documentation | Qiskit

### ISSUE THREAD

**Issue by aryashah2k** [proRamLOGO/quantum-algorithms#4]
Hi @proRamLOGO , I'm Arya and I am a participant in Crosswoc, I would like to contribute to your repository with different Quantum Algorithms and Quantum Implementations in Qiskit and Q#, I am planning to open issues which will tremendously help this repository and enhance the amount of content for the same. Please acknowledge my willingness to contrinute towards your project and assign this issue to me!

For the file structure I am thinking of creating folders for each framework and then add subdirectories within them for each unique algorithm.

Awaiting your response! 
**Please add the relevant Label for Crosswoc for this issue**
 - good-first-issue is 50 points
 - difficulty: easy is 100 points
 - difficulty: medium is 200 points
 - difficulty: hard is 500 points

Regards,
Arya

**Comment by proRamLOGO** [comment]
Required Tags have been added

**Comment by proRamLOGO** [comment]
Pull request for implementation of Deutsch Josza Algorithm in Q# has been merged. However, this issue is for the Qiskit implementation for the same and still stands open.

**Comment by aryashah2k** [comment]
Yes @proRamLOGO  I shall start working on this and create PR soon tha Ka for merging my two PRs previously!
