### ISSUE TITLE
Add CHSH Algorithm Implementation | Qiskit

### ISSUE THREAD

**Issue by aryashah2k** [proRamLOGO/quantum-algorithms#8]
@proRamLOGO , Similar to the issue #7  where implementation is to be done in Q#, I am opening this issue to add implementation of the same in Qiskit Framework.

Do consider assigning this issue to me and I shall start my work right away!

**Please add the relevant Label for Crosswoc for this issue**

good-first-issue is 50 points
difficulty: easy is 100 points
difficulty: medium is 200 points
difficulty: hard is 500 points

Regards,
Arya

**Comment by proRamLOGO** [comment]
Pull request for implementation of CHSH Algorithm in Q# has been merged. However, this issue is for the Qiskit implementation for the same and still stands open.
